# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build:
   description: Private.
    steps:
      - run:
         name: Zip build
         working_directory: /tmp/workspace/output
         command: |
           zip -r /tmp/client_upload/build.zip *
      - run:
         name: Zip environment definitions
         working_directory: /tmp/workspace
         command: >
           zip -r /tmp/client_upload/environment.zip environment_definitions.json
           environments

  # job to upload to Veracode for scanning
  veracode_scan:

    # use a java-based image to run the Veracode API wrapper
    docker:
      - image: signiant/docker-jenkins-centos7-java8:latest
      
    #working_directory: ~/target
    
    steps:
      # get the files from the previous job
      - attach_workspace:
          at: ./
          
      # grab the Veracode agent
      - run:
          name: "Get the Veracode agent"
          command: |
             curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
             java -jar /opt/veracode/pipeline-scan.jar --veracode_api_id="3d43e6c19ba62a029b4d74ef3274f64e" --veracode_api_key="bcbf7a5c957bb8495ec1be6dbd71a7b6b7549eaed57bd04a81b9d4ec5f61c3c8d634bc68c8139828d0c714bdb1bac088304391e9043f59207801e6cdc062271e " --fail_on_severity="Very High, High" --file="project.zip" --app_id="1231145" --json_output_file="results.json"
 
 ALYSISCENTER_KEY" --source_dir "./" --build_dir "./target" --project_name "Verademo_circleci" --project_url $SRCCLR_SCM_URI --previous_job_name $CIRCLE_PREVIOUS_BUILD_NUM --source_dir "./" --build_dir "./target" --project_name "Verademo_circleci" --project_url $SRCCLR_SCM_URI --previous_job_name $CIRCLE_PREVIOUS_BUILD_NUM
# serial jobs - need to run 'build' before 'scan'
workflows:
  version: 2.1
  build_and_scan:
    jobs:
      - build
      - veracode_scan:
          requires:
            - build
    